---
- name: Encryption keys | Get encrypted pools
  ansible.builtin.set_fact:
    zfs_encrypted_pools: >-
      {{ zfs_pools | selectattr('options', 'search', 'keylocation')
      | map(attribute='name') | list }}
  when: zfs_create_pools

- name: Encryption keys | Get encrypted datasets
  ansible.builtin.set_fact:
    zfs_encrypted_datasets: >-
      {{ zfs_filesystems
        | selectattr('keylocation', 'defined')
        | map(attribute='pool') | zip(zfs_filesystems | map(attribute='name'))
        | map('join', '\x2d') | list
      }}
  when: zfs_create_filesystems

- debug:
    var: zfs_encrypted_datasets

- name: Encryption keys | Create key-load service unit file
  ansible.builtin.template:
    src: etc/systemd/system/zfs-load-key@.service.j2
    dest: /etc/systemd/system/zfs-load-key@.service
    owner: root
    group: root
    mode: "0644"
  when: >-
    zfs_encrypted_pools | default([]) | length > 0
    or zfs_encrypted_datasets | default([]) | length > 0

- name: Encryption keys | Activate key-load service for encrypted pools
  ansible.builtin.systemd_service:
    name: zfs-load-key@{{ item }}
    enabled: true
  loop: "{{ zfs_encrypted_pools }}"
  when: zfs_create_pools

- name: Encryption keys | Activate key-load service for encrypted datasets
  ansible.builtin.systemd_service:
    name: zfs-load-key@{{ item }}
    enabled: true
  loop: "{{ zfs_encrypted_datasets }}"
  when: zfs_create_filesystems
